# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/a_02.ipynb.

# %% auto 0
__all__ = ['return_two', 'TestFunc1', 'rand_number', 'test_func_1', 'test_func_2']

# %% ../../nbs/a_02.ipynb 3
import pytest

# %% ../../nbs/a_02.ipynb 10
@pytest.fixture()
def return_two():
    yield
    a = 2

# %% ../../nbs/a_02.ipynb 13
@pytest.mark.usefixtures("return_two")
class TestFunc1:
    def test_one(self):
        assert self.a == 2

# %% ../../nbs/a_02.ipynb 15
import random

# %% ../../nbs/a_02.ipynb 16
@pytest.fixture
def rand_number(scope="module"):
    return random.randint(0, 99)

# %% ../../nbs/a_02.ipynb 18
def test_func_1(rand_number):
    assert rand_number == 2

# %% ../../nbs/a_02.ipynb 19
def test_func_2(rand_number):
    assert rand_number == 2
