# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/06_tests.test_api.ipynb.

# %% auto 0
__all__ = ['pytestmark', 'test_connect_db', 'test_init_db']

# %% ../../nbs/06_tests.test_api.ipynb 3
import pytest

# %% ../../nbs/06_tests.test_api.ipynb 5
pytestmark = pytest.mark.skip

# %% ../../nbs/06_tests.test_api.ipynb 6
def test_connect_db():
    pass

# %% ../../nbs/06_tests.test_api.ipynb 7
def test_init_db():
    pass
