# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/00_pytest_fixture.ipynb.

# %% auto 0
__all__ = ['Book', 'notebook', 'test_book', 'Vehicle', 'car', 'test_car', 'Tree']

# %% ../../nbs/00_pytest_fixture.ipynb 3
import pytest

# %% ../../nbs/00_pytest_fixture.ipynb 4
class Book:
    def __init__(self, name):
        self.name = name

# %% ../../nbs/00_pytest_fixture.ipynb 7
@pytest.fixture
def notebook() -> Book:
    return Book("Zoo Adventure")

# %% ../../nbs/00_pytest_fixture.ipynb 8
def test_book(notebook):
    assert notebook.name == "Zoo Adventure"

# %% ../../nbs/00_pytest_fixture.ipynb 10
class Vehicle:
    def __init__(self, name): self.name = name

# %% ../../nbs/00_pytest_fixture.ipynb 14
@pytest.fixture
def car(**kwargs):
    
    def _car(**kwargs):
        return Vehicle(kwargs).name

    return _car

# %% ../../nbs/00_pytest_fixture.ipynb 15
@pytest.mark.xfail
def test_car(car):
    c1 = car(name="Truck")
    c2 = car(name="Bus")
    
    assert c1 == "Truck"
    assert c2 == "Bus"

# %% ../../nbs/00_pytest_fixture.ipynb 17
class Tree:
    def __init__(self, name): self.name = name
