# AUTOGENERATED! DO NOT EDIT! File to edit: ../03_first_project.ipynb.

# %% auto 0
__all__ = ['avg']

# %% ../03_first_project.ipynb 1
# calculate the average of a list of numbers
def avg(*list_numbers):
    total = 0
    for num in list_numbers:

        if isinstance(num, (int, float)):
            total += num
        else:
            raise TypeError("Wrong input data")

    return total / len(list_numbers)
