# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/learn_pytest',
                'doc_host': 'https://.github.io',
                'git_url': 'https://github.com//learn_pytest',
                'lib_path': 'learn_pytest'},
  'syms': { 'learn_pytest.core': {'learn_pytest.core.foo': ('core.html#foo', 'learn_pytest/core.py')},
            'learn_pytest.test_fn': { 'learn_pytest.test_fn.test_func_1': ('test_fn.html#test_func_1', 'learn_pytest/test_fn.py'),
                                      'learn_pytest.test_fn.test_func_2': ('test_fn.html#test_func_2', 'learn_pytest/test_fn.py'),
                                      'learn_pytest.test_fn.test_func_3': ('test_fn.html#test_func_3', 'learn_pytest/test_fn.py'),
                                      'learn_pytest.test_fn.test_func_4': ('test_fn.html#test_func_4', 'learn_pytest/test_fn.py')}}}