# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/learn-sympy',
                'doc_host': 'https://xrsrke.github.io',
                'git_url': 'https://github.com/xrsrke/learn-sympy',
                'lib_path': 'learn_sympy'},
  'syms': {'learn_sympy.core': {'learn_sympy.core.foo': ('core.html#foo', 'learn_sympy/core.py')}}}