# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/learn-scipy',
                'doc_host': 'https://xrsrke.github.io',
                'git_url': 'https://github.com/xrsrke/learn-scipy',
                'lib_path': 'learn_scipy'},
  'syms': {'learn_scipy.basic': {}, 'learn_scipy.core': {'learn_scipy.core.foo': ('core.html#foo', 'learn_scipy/core.py')}}}