# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/10_performance_testing.ipynb.

# %% auto 0
__all__ = ['slow_func', 'test_slow_func']

# %% ../../nbs/10_performance_testing.ipynb 5
import pytest
from unittest import TestCase

# %% ../../nbs/10_performance_testing.ipynb 6
import pytest

# %% ../../nbs/10_performance_testing.ipynb 7
def slow_func():
    x = 1
    for i in range(1, 10):
        x += x**i

# %% ../../nbs/10_performance_testing.ipynb 8
@pytest.mark.performance
def test_slow_func():
    slow_func()
