# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/00_pytest_parametrize.ipynb.

# %% auto 0
__all__ = ['square', 'test_square_one', 'test_square_two', 'test_square', 'power_two', 'test_power']

# %% ../../nbs/00_pytest_parametrize.ipynb 3
import pytest
from unittest import TestCase

# %% ../../nbs/00_pytest_parametrize.ipynb 4
def square(x):
    return x * x

# %% ../../nbs/00_pytest_parametrize.ipynb 5
def test_square_one():
    assert square(1) == 1

# %% ../../nbs/00_pytest_parametrize.ipynb 6
def test_square_two():
    assert square(2) == 4

# %% ../../nbs/00_pytest_parametrize.ipynb 8
@pytest.mark.parametrize(
    ("test_input", "expected"),
    ((1, 1), (2, 4))
)
def test_square(test_input, expected):
    assert square(test_input) == expected

# %% ../../nbs/00_pytest_parametrize.ipynb 10
def power_two(x):
    return x ** 2

# %% ../../nbs/00_pytest_parametrize.ipynb 11
@pytest.mark.parametrize(
    ("test_input", "expected"),
    (pytest.param(5, 25, id="power_of_5"),)
)
def test_power(test_input, expected):
    assert power_two(test_input) == expected
