# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/pytest_django',
                'doc_host': 'https://xrsrke.github.io',
                'git_url': 'https://github.com/xrsrke/pytest_django',
                'lib_path': 'pytest_django'},
  'syms': {'pytest_django.core': {'pytest_django.core.foo': ('core.html#foo', 'pytest_django/core.py')}}}