# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/learn-numpy',
                'doc_host': 'https://xrsrke.github.io',
                'git_url': 'https://github.com/xrsrke/learn-numpy',
                'lib_path': 'learn_numpy'},
  'syms': {'learn_numpy.core': {'learn_numpy.core.foo': ('core.html#foo', 'learn_numpy/core.py')}}}